import os
import base64
from github import Github
from dotenv import load_dotenv

load_dotenv()

def create_pr(pipeline_result: dict) -> str:
    print("🤖 GitHub Agent started...")

    g = Github(os.getenv("GITHUB_TOKEN"))
    repo = g.get_repo(f"{os.getenv('GITHUB_REPO_OWNER')}/{os.getenv('GITHUB_REPO_NAME')}")

    # Create branch name from feature
    feature = pipeline_result["feature"]
    branch_name = "specdeploy/" + feature.lower().replace(" ", "-").replace("'", "")[:50]

    # Get main branch
    main = repo.get_branch("main")

    # Create new branch
    try:
        repo.create_git_ref(
            ref=f"refs/heads/{branch_name}",
            sha=main.commit.sha
        )
        print(f"✅ Branch created: {branch_name}")
    except Exception as e:
        print(f"⚠️ Branch might exist: {e}")

    # Commit all files
    for file in pipeline_result["files"]:
        filename = file["filename"]
        content = file["content"]

        try:
            # Check if file exists
            existing = repo.get_contents(filename, ref=branch_name)
            repo.update_file(
                path=filename,
                message=f"feat: add {filename} via SpecDeploy",
                content=content,
                sha=existing.sha,
                branch=branch_name
            )
        except:
            # File doesn't exist, create it
            repo.create_file(
                path=filename,
                message=f"feat: add {filename} via SpecDeploy",
                content=content,
                branch=branch_name
            )
        print(f"  📄 Committed: {filename}")

    # Open PR
    pr = repo.create_pull(
        title=f"feat: {feature} [SpecDeploy]",
        body=f"""## 🤖 Generated by SpecDeploy

**Feature Request:** {feature}

## What's included
- 📋 Feature Spec (SPEC.md)
- 💻 Implementation code
- 🧪 Tests
- ⚙️ CI/CD Pipeline

## Spec Preview
{pipeline_result['spec'][:500]}...

---
*This PR was automatically generated by SpecDeploy — Natural Language → Production Pipeline*
""",
        head=branch_name,
        base="main"
    )

    print(f"✅ PR Created: {pr.html_url}")
    return pr.html_url