```json
{
  "files": [
    {
      "filename": "tests/test_stripe_payment.py",
      "content": "import pytest\nfrom stripe_payment import app, db, Payment\nfrom flask import json\nimport stripe\n\n@pytest.fixture\ndef client():\n    app.config['TESTING'] = True\n    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///test_payment.db'\n    db.create_all()\n    yield app.test_client()\n    db.session.remove()\n    db.drop_all()\n\ndef test_make_payment_happy_path(client):\n    data = {'user_id': 1, 'payment_method': 'pm_card_visa', 'amount': 100, 'email': 'test@example.com'}\n    response = client.post('/payment', data=json.dumps(data), content_type='application/json')\n    assert response.status_code == 200\n    assert json.loads(response.data)['message'] == 'Payment successful'\n\ndef test_make_payment_error_case(client):\n    data = {'user_id': 1, 'payment_method': 'invalid', 'amount': 100, 'email': 'test@example.com'}\n    response = client.post('/payment', data=json.dumps(data), content_type='application/json')\n    assert response.status_code == 400\n    assert json.loads(response.data)['message'] == 'Payment failed'\n\ndef test_make_payment_edge_case(client):\n    data = {'user_id': 1, 'payment_method': 'pm_card_visa', 'amount': 0, 'email': 'test@example.com'}\n    response = client.post('/payment', data=json.dumps(data), content_type='application/json')\n    assert response.status_code == 500\n    assert 'amount must be greater than zero' in json.loads(response.data)['message']\n\ndef test_payment_history_happy_path(client):\n    payment = Payment(1, 'pm_card_visa', 100, 'succeeded')\n    db.session.add(payment)\n    db.session.commit()\n    response = client.get('/payment/history')\n    assert response.status_code == 200\n    assert len(json.loads(response.data)) == 1\n\ndef test_payment_history_error_case(client):\n    response = client.get('/payment/history')\n    assert response.status_code == 200\n    assert len(json.loads(response.data)) == 0\n\ndef test_make_payment_invalid_request(client):\n    data = {'user_id': 1, 'payment_method': 'pm_card_visa'}\n    response = client.post('/payment', data=json.dumps(data), content_type='application/json')\n    assert response.status_code == 500\n    assert 'amount' in json.loads(response.data)['message']\n\ndef test_make_payment_invalid_amount(client):\n    data = {'user_id': 1, 'payment_method': 'pm_card_visa', 'amount': 'invalid', 'email': 'test@example.com'}\n    response = client.post('/payment', data=json.dumps(data), content_type='application/json')\n    assert response.status_code == 500\n    assert 'amount must be a number' in json.loads(response.data)['message']"
    },
    {
      "filename": "tests/test_routes.py",
      "content": "import pytest\nfrom routes import routes\nfrom flask import json\n\n@pytest.fixture\ndef client():\n    app = routes\n    app.config['TESTING'] = True\n    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///test_payment.db'\n    yield app.test_client()\n    app.session.remove()\n    app.drop_all()\n\ndef test_make_payment_happy_path(client):\n    data = {'user_id': 1, 'payment_method': 'pm_card_visa', 'amount': 100, 'email': 'test@example.com'}\n    response = client.post('/payment', data=json.dumps(data), content_type='application/json')\n    assert response.status_code == 200\n    assert json.loads(response.data)['message'] == 'Payment successful'\n\ndef test_payment_history_happy_path(client):\n    payment = Payment(1, 'pm_card_visa', 100, 'succeeded')\n    db.session.add(payment)\n    db.session.commit()\n    response = client.get('/payment/history')\n    assert response.status_code == 200\n    assert len(json.loads(response.data)) == 1"
    },
    {
      "filename": "tests/test_config.py",
      "content": "import pytest\nfrom config import STRIPE_SECRET_KEY, STRIPE_PUBLISHABLE_KEY, MAIL_SERVER, MAIL_PORT, MAIL_USE_TLS, MAIL_USERNAME, MAIL_PASSWORD\n\ndef test_config():\n    assert STRIPE_SECRET_KEY == 'stripe_secret_key'\n    assert STRIPE_PUBLISHABLE_KEY == 'stripe_publishable_key'\n    assert MAIL_SERVER == 'smtp.gmail.com'\n    assert MAIL_PORT == 587\n    assert MAIL_USE_TLS == True\n    assert MAIL_USERNAME == 'email@gmail.com'\n    assert MAIL_PASSWORD == 'email_password'"
    }
  ]
}
```